# Generated by Django 5.0.1 on 2024-01-05 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('home', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.categories')),
                ('sub_variant', models.ManyToManyField(blank=True, related_name='products', to='api.subvariants')),
                ('variant', models.ManyToManyField(blank=True, related_name='products', to='api.variants')),
            ],
        ),
        migrations.CreateModel(
            name='SalesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'invoiced'), (2, 'delivered'), (3, 'returned')], default=0)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.addresses')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customers')),
            ],
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salesmaster')),
                ('sub_variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.subvariants')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.variants')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('qty', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.products')),
                ('sub_variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.subvariants')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.variants')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='product/')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variants')),
            ],
        ),
    ]
