# Generated by Django 5.0.1 on 2024-01-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='sub_variant',
            new_name='sub_variants',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='variant',
            new_name='variants',
        ),
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
