# Generated by Django 5.0.1 on 2024-01-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_sub_variant_products_sub_variants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subvariants',
            name='description',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='description',
        ),
    ]
