# Generated by Django 5.0.1 on 2024-01-06 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.products'),
            preserve_default=False,
        ),
    ]
